#install.packages('Seurat')
#install.packages('Signac')
#if (!require("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")

#BiocManager::install("BiocGenerics")
#BiocManager::install("GenomeInfoDb")
#BiocManager::install("GenomicRanges")
#BiocManager::install("Rsamtools")
#BiocManager::install("SummarizedExperiment")
#BiocManager::install("SingleCellExperiment")
#devtools::install_github("JiekaiLab/dior")

#library(SeuratDisk)
library(Seurat)
library(BiocGenerics)
library(GenomeInfoDb)
library(GenomicRanges)
library(Rsamtools)
library(Signac)
library(SummarizedExperiment)
library(SingleCellExperiment)

pbmc.data <- readRDS('../Downloads/combined_filtered.rds')
#SaveH5Seurat(pbmc.data, '../Downloads/combined_filtered.h5', overwrite = FALSE, verbose = TRUE)
dior::write_h5(pbmc.data, file='../Downloads/combined_filtered.h5', object.type = 'seurat')
d1 = as.data.frame(pbmc.data@assays$chromvar[])
write.csv(d1,'C:/Users/amonell/Downloads/chromvar_data.csv')
